import express, { Router } from 'express';
import {
  signUpOwner,
  loginUser,
  getCurrentUser,
  logoutUser,
  acceptInvite,
  inviteUser,
} from '../controller/authController';
import { requireRoles, verifyJWT } from '../middlewares/authMiddleware';

const router: Router = express.Router();
// Public
router.post('/signup', signUpOwner);
router.post('/login', loginUser);
router.post('/accept-invite', acceptInvite);

// Protected (requires Bearer token generated by signIn/signUp)
router.get('/me', verifyJWT, getCurrentUser);
router.post('/logout', verifyJWT, logoutUser);

router.post('/invite', verifyJWT, requireRoles(['OWNER', 'MANAGER']), inviteUser);

export default router;
